apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: chat-app-cert
  namespace: default
spec:
  secretName: chat-app-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s-diary.chat-app.com
  dnsNames:
   - k8s-diary.chat-app.com
  acme:
   config:
    - http01:
       ingress: frontend-ingress
      domains:
       - k8s-diary.chat-app.com