version: '1.0'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: chat-server
    container_name: chat-node-server
    ports:
      - '${PORT}:${PORT}'
    env_file: .env
    environment:
       - NODE_ENV=development
    networks:
      - chat-netowrk
  
  database:
    image: mongo:latest
    container_name: chat-mongo
    hostname: mongodbserver
    env_file: .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
     - ./docker-volumes/mongo:/data/db
    networks:
    - chat-netowrk

networks:
  app-netowrk:
   name: chat-netowrk