# This is a basic workflow that is manually triggered

name: Node.js CI

on:
  push:
    branches:  [main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x ]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Fetch dependencies
        working-directory: server
        run: npm install

      - name: Build project
        working-directory: server
        run: yarm install

      - name: Test project
        working-directory: server
        run: yarn test
        