version: '3.8'

services:
  redis:
    image: redis:alpine
    restart: always

  chat:
    image: nina/pvs-chat-app
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
