version: '1.0'

services:
  server-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: chat-server-dev
    container_name: chat-server-dev
    ports:
      - '${PORT}:${PORT}'
    
    env_file: .env
    environment:
     - NODE_ENV=development
    volumes:
      - ./:usr/src/app
      - /usr/src/app/node_modules/
    command: 'yarn run dev:debug'
    networks:
     - chat-netowrk
    
  database-dev:
    image: mongo:latest
    container_name: chat-database-dev
    hostname: mongodbserver
    env_file: .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./docker-volumes/mongo:/data/db
    networks:
      - chat-netowrk

networks:
  chat-network:
   name: chat-network